name: mariaelena
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05938
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0c0c0'
    - '#227fbc'
    - '#000000'
    - '#ffffff'
    - '#00ffff'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
